### ISSUE TITLE
Uncaught TypeError: Return value of HeadlessChromium\PageUtils\PageScreenshot::getException() must be an instance of Exception, none returned

### ISSUE THREAD

**Issue by momala454** [chrome-php/chrome#107]
Uncaught TypeError: Return value of HeadlessChromium\PageUtils\PageScreenshot::getException() must be an instance of Exception, none returned in /headless-chromium-php/vendor/chrome-php/chrome/src/PageUtils/PageScreenshot.php:21
Stack trace:
#0 headless-chromium-php/vendor/chrome-php/chrome/src/PageUtils/AbstractBinaryInput.php(44): HeadlessChromium\PageUtils\PageScreenshot-&gt;getException('-32000 - Cannot...')
#1 test.php(174): HeadlessChromium\PageUtils\AbstractBinaryInput-&gt;getBase64()
#2 {main}
  thrown in <b>headless-chromium-php/vendor/chrome-php/chrome/src/PageUtils/PageScreenshot.php</b> on line <b>21</b><br />

command :
$page->screenshot(array('clip' => $page->getFullPageClip()))->getBase64()

**Comment by GrahamCampbell** [comment]
Not stale.

**Comment by momala454** [comment]
bot, stap !

**Comment by momala454** [comment]
no

**Comment by GrahamCampbell** [comment]
Is this bug still happening? Looking at the code, I can't see why this would be happening.

**Comment by momala454** [comment]
maybe not, fixing by this : 
https://github.com/chrome-php/chrome/commit/9edc9bb88ef4f9f0b4c52a703a3867b866b25f76#diff-91d162b0f4c9feae021cb120920deb5731c3e44afa273350bf9f94d74dbf767a
