### ISSUE TITLE
memory leak in evaluate

### ISSUE THREAD

**Issue by Netmosfera** [chrome-php/chrome#114]
this code causes the process to increase the memory usage every time it is called.

`$this->page->evaluate($javascript)->getReturnValue($this->timeout)`

it is quite noticeable when calling it many many times.

the process eventually dies because it runs out of memory

**Comment by 530513750** [comment]
yes, I have the same problem

**Comment by momala454** [comment]
do you have an code example ? i am not able to reproduce

**Comment by momala454** [comment]
apparently this fix from the library wrench fix the leak :
https://github.com/varspool/Wrench/commit/6257a25ca5e23233533e2462250478d8d7841634

could you both try and report ?

wrench have not been updated / packaged since that change unfortunately

**Comment by t-geindre** [comment]
Temporary fix https://github.com/chrome-php/headless-chromium-php/issues/68#issuecomment-466940843

**Comment by momala454** [comment]
don't close

**Comment by momala454** [comment]
no

**Comment by GrahamCampbell** [comment]
Already fixed. We use our own fork for wrench now.
