### ISSUE TITLE
choosing ip address?

### ISSUE THREAD

**Issue by Marcophono2** [chrome-php/chrome#173]
Hello!
There are 24 ip addresses binded to my server. Is it possible to tell headless-chromium which of that ip addresses it shall use for the remote accesses? As far as I understand this is something different as the "proxy" option. What I need is a forward proxy. Or am I wrong?

Best regards
Marc

**Comment by alex-rsk** [comment]
I think, it is question more to system administrators, than for programmers. 
The key question is, how to "point" your WAN connection to the certain IP address, I think.
Maybe you have to manage IPTables for it.

**Comment by h2lsoft** [comment]
Will it support chrome flag  --proxy-server ?

**Comment by Oregon09** [comment]
https://medium.com/@havloujian.joachim/advanced-docker-networking-outgoing-ip-921fc3090b09

or 

https://docs.docker.com/network/macvlan/

it's good ?

**Comment by Marcophono2** [comment]
@Oregon09 That are good hints. Thanks a lot, Oregon! I'll try this out.

Best regards
Marc
