### ISSUE TITLE
Finding element by id and click mouse only first time works.

### ISSUE THREAD

**Issue by upmanager** [chrome-php/chrome#292]
`
     // test.php file

    $browserFactory = new BrowserFactory();
    $browser = $browserFactory->createBrowser([
        'windowSize'      => [1920, 1000],
        'headless' => false
    ]);
    $page = $browser->createPage();
    $page->navigate('http://localhost/index.html')->waitForNavigation();
    sleep(1);
    $page->mouse()->find('#test1')->click();
    sleep(5);
    $page->mouse()->find('#test2')->click();
    sleep(5);
`

`
index.html file

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>test</title>
    </head>
    <body>
        <a href="#1" id="test1"> test 1</a>
        <a href="#2" id="test2"> test 2</a>
    </body>
    </html>
`

If I execute the test.php file, The URL must change to like this
first: localhost/index.php
after 1 second: localhost/index.php#1
after 1 sec again: localhost/index.php#2
but it's click #test1, but not click the test2. 
What is wrong with my code?
Give me the solution soo, Thank you.

**Comment by upmanager** [comment]
I just saw one that click dom element.
https://github.com/chrome-php/chrome/tree/1.2#interacting-with-dom
Is it working well?   how can I use this 1.2 version?
When be you will release it?

**Comment by laurin1** [comment]
I believe this is the same issue that I am having: https://github.com/chrome-php/chrome/issues/272
