### ISSUE TITLE
How to use http proxy?

### ISSUE THREAD

**Issue by robinhunan** [chrome-php/chrome#30]
Thanks a lot!

**Comment by gsouf** [comment]
Hi @robinhunan 

That's not possible yet, but that's just the matter of adding the right flags on startup. That's an easy pick and it can be implemented soon

**Comment by amhoho** [comment]
+1

**Comment by Alinka24789** [comment]
Hi @gsouf 

Could you tell, please, when proxy options will be available?

**Comment by bravedave** [comment]
On my Fedora machine:
new \HeadlessChromium\BrowserFactory( 'google-chrome --proxy-server="socks5://localhost:1080"');

You can see the format for the proxy server settings here:
https://www.chromium.org/developers/design-documents/network-settings

**Comment by gsouf** [comment]
Hi @Alinka24789 

As @bravedave just pointed it out you can pass the proxy flag, or you can also use the option ``customFlags``:

```php
$browserFactory->createBrowser([
        'customFlags' => [
            '--proxy-server="socks5://localhost:1080"'
       ]
]);
```

I'll still add an option dedicated to proxies to abstract its usage
