### ISSUE TITLE
How to make authenticate for Chromium PHP like Puppeteer?

### ISSUE THREAD

**Issue by DenisSokoloff** [chrome-php/chrome#367]
Chromium does not support credential proxy but I found it at **Puppeteer**

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--proxy-server=IP:PORT']
  });
  const page = await browser.newPage();
    await page.authenticate({
        username: 'USER',
        password: 'PASSWORD'
    });
    await page.goto('http://lumtest.com/myip.json');
    await page.screenshot({path: 'example.png'});
    await browser.close();
})();
```

In source 
https://github.com/puppeteer/puppeteer/blob/main/src/common/NetworkManager.ts

```
const { username, password } = this._credentials || {
      username: undefined,
      password: undefined,
    };
    this._client
      .send('Fetch.continueWithAuth', {
        requestId: event.requestId,
        authChallengeResponse: { response, username, password },
      })
```

I am looking for solution, but if you have, write it there

**Comment by DenisSokoloff** [comment]
I have try Puppeteer functionality, but **authRequired** event do not call by Chromium and auth stops

```
$page->getSession()->on('method:Fetch.authRequired', function (array $params): void
        {
            var_dump("method:Fetch.authRequired");
            var_dump($params);

            $params1                            = [];
            $params1["requestId"]               = $params["requestId"];
            $params1["authChallengeResponse"]   = array('response' => "ProvideCredentials", 'username' => "USER", 'password' => "PASSWORD");
            $this->_page->getSession()->sendMessage(new HeadlessChromium\Communication\Message('Fetch.continueWithAuth',  $params1));
        });


        $page->getSession()->on('method:Fetch.requestPaused', function (array $params): void
        {
            var_dump("method:Fetch.requestPaused");
            var_dump($params);
        });

        $page->getSession()->on('method:Page.lifecycleEvent', function (array $params): void
        {
            var_dump("method:Page.lifecycleEvent");
            var_dump($params);
        });

        $params2                          = [];
        $params2["handleAuthRequests"]    = true;
        $params2["patterns"]              = [array('urlPattern' => '*')];
        $page->getSession()->sendMessage(new HeadlessChromium\Communication\Message('Fetch.enable',            $params2));

        $navigation = $page->navigate($url);
        $navigation->waitForNavigation(\HeadlessChromium\Page::NETWORK_IDLE, 30000);
```

Looks like proxy server does not sent AUTH recurrence, and my auth stops.
Stay code there, maybe be useful

**Comment by DenisSokoloff** [comment]
Final solution:

`if (($user) && ($pass))
        {
            $page->getSession()->on('method:Fetch.authRequired', function (array $params): void
            {
               $this->_page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Fetch.continueWithAuth', array('requestId' => $params["requestId"], 'authChallengeResponse' => array('response' => 'ProvideCredentials', 'username'=> $this->_user, 'password' => $this->_pass))));
            });
            $page->getSession()->on('method:Fetch.requestPaused', function (array $params): void
            {
                $this->_page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Fetch.continueRequest', array('requestId' => $params["requestId"])));
            });

            $page->getSession()->sendMessageSync(new \HeadlessChromium\Communication\Message('Fetch.enable', array("handleAuthRequests" => true, "patterns" => [array('urlPattern' => '*')])));

        }`

**Comment by Surzhikov** [comment]
@DenisSokoloff big thanks for solution.

@enricodias, It seems that many people are interested in this method of proxy authentication (instead of installing MIMT proxy, etc). It might be worth adding a description of this method to the README.

I formatted the solution neatly as a gist:
https://gist.github.com/Surzhikov/002a85ed0a9da7b126b5fc356f281426

**Comment by DenisSokoloff** [comment]
> @DenisSokoloff big thanks for solution.
> 
> @enricodias, It seems that many people are interested in this method of proxy authentication (instead of installing MIMT proxy, etc). It might be worth adding a description of this method to the README.
> 
> I formatted the solution neatly as a gist: https://gist.github.com/Surzhikov/002a85ed0a9da7b126b5fc356f281426

Welcome!
