### ISSUE TITLE
Get response status code

### ISSUE THREAD

**Issue by vcalderonoyarce** [chrome-php/chrome#41]
I need to get response status code, what can I do?

**Comment by gsouf** [comment]
Hi @vcalderonoyarce 

That's not possible yet, need to be implemented in the library.

Will try to do that in the week as it's an important feature.

**Comment by vcalderonoyarce** [comment]
> Hi @vcalderonoyarce
> 
> That's not possible yet, need to be implemented in the library.
> 
> Will try to do that in the week as it's an important feature.

Hi, thanks! I would really appreciate it.

**Comment by mschwerin** [comment]
Until this is supported:

```
        /* Catch HTTP status code. */
        $statusCode = 500;
        $statusText = "Internal server error";
        $page->getSession()->on("method:Network.responseReceived",
            function($params) use (&$statusCode, &$statusText)
            {
                $statusCode = $params["response"]["status"];
                $statusText = $params["response"]["statusText"];
            }
        );
```

**Comment by Meeshalk** [comment]
Is this feature implemented in the library?

**Comment by BenMorel** [comment]
Looking forward to this feature as well.

**Comment by BenMorel** [comment]
Looking forward to this feature as well.

@mschwerin I guess this returns the HTTP status code for all network requests, not just the one from the main page?

**Comment by raykudo** [comment]
+1 not only status code but all the response contents preferably

**Comment by BenMorel** [comment]
Good bot. Still relevant.

**Comment by ZaneCEO** [comment]
https://github.com/chrome-php/chrome/issues/41#issuecomment-447047235 is a good workaround (thanks pal!), but it fails with a customized 404 page such as https://turbolabit.github.io/html-pages/non-existant.html  because the event fires for every asset of the page, including the small 200-returning GitHub logo.

I switched to `$page->getSession()->once()` (**once()** instead of **on()**) ad it worked but, again, a clean method is very much needed

**Comment by otsch** [comment]
+1!

**Comment by miguelfrmn** [comment]
+1

**Comment by AlexeyKosov** [comment]
@gsouf
Please re-open

**Comment by enricodias** [comment]
I'll try to implement this.

**Comment by aravael** [comment]
Hi @enricodias . Any updates on when your very needed feature will be implemented?

**Comment by enricodias** [comment]
@aravael not yet 😅

**Comment by professional-sourav** [comment]
Is there a way to get the response of non html content, like image, js or css?

**Comment by aravael** [comment]
@professional-sourav , try and analyze the below code. `Network.responseReceived` catches all the requests completed on the page, 
```
$page->getSession()->on("method:Network.responseReceived", function (array $params): void {
    var_dump($params);
});
```

**Comment by professional-sourav** [comment]
> @professional-sourav , try and analyze the below code. `Network.responseReceived` catches all the requests completed on the page,
> 
> ```
> $page->getSession()->on("method:Network.responseReceived", function (array $params): void {
>     var_dump($params);
> });
> ```

Thanks. But I am not getting the response body. I am getting headers and other data but the body is missing in the response. How can I get the body as well? 

Right now, I need to call the getHtml() to get the html. But for resources like css, js and images I am not getting the raw data.

**Comment by enricodias** [comment]
@professional-sourav the response received has a `Response` field with the response data, see https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceived

This response data has a `Headers` field, see https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Response

**Comment by scorpio1441** [comment]
Still no reliable method of getting all headers.
Latest version of Chrome (117).
Every code I tried above - won't work.
Please?
